version: 1
update_configs:
  - package_manager: "github_actions"
    directory: "/"
    update_schedule: "daily"
    default_reviewers: ["imbsky"]
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_reviewers: ["imbsky"]
