name: Main workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore yarn cache
        uses: actions/cache@preview
        id: yarn
        with:
          path: node_modules
          # prettier-ignore
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Restore esy cache
        uses: actions/cache@preview
        id: esy
        with:
          path: ~/.esy
          # prettier-ignore
          key: ${{ runner.os }}-esy-${{ hashFiles(format('{0}{1}', github.workspace, '/esy.lock/index.json')) }}

      - name: Install esy
        run: npm install --global esy

      - name: Install Node.js packages
        if: steps.yarn.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - name: Install and build OCaml packages
        if: steps.esy.outputs.cache-hit != 'true'
        run: esy

      - name: Cleanup
        run: yarn clean

      - name: Extract to OCaml
        run: |
          cd ocaml
          esy coqc ../coq/*.v

      - name: Compile OCaml to JavaScript
        run: yarn build
